name: CI and CD data model

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:
  retraining_model:
    runs-on: ubuntu-latest
    container: docker//dvcorg/cml:latest
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run:
          pip3 install -r requirements.txt

      - name: Execute the training model
        run: |
          python3 retraining.py

      - name: Generating report
        run: |
          echo "# Model metrics" > report.md
          
          echo "## Training accuracy" >> report.md
          cat metrics.txt >> report.md
          
          echo "## Data visualization" >> report.md
          cml-publish feature_importance.png --md >> report.md
          
          cml-send-comment report