name: CI and CD data model

on:
  push:
    branches:
      - stage
  pull_request:
    branches:
      - stage

jobs:
  retraining_model:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml:latest

    env:
      repo_token: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run:
          pip3 install -r requirements.txt

      - name: Execute the training model
        run: |
          python3 retraining.py

      - name: Generating report
        run: |
          echo "# Model metrics" > report.md
          echo "## Training accuracy" >> report.md
          
          if [ -f metrics.txt ]; then
            cat metrics.txt >> report.md
          else
            echo "No metrics available" >> report.md
          fi
          
          echo "## Data visualization" >> report.md
          
          if [ -f feature_importance.png ]; then
            cml comment create "![Feature Importance](feature_importance.png)" --target report.md
          else
            echo "No feature importance image found" >> report.md
          fi

      - name: Post report comment
        run: cml comment create report.md