name: CI model to dockerhub

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  retraining_model:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    container: docker://dvcorg/cml:latest
    env:
      repo_token: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install requirements
        run:
          pip3 install -r requirements.txt

      - name: Execute the training model
        run: |
          python3 retraining.py

      - name: Generating report
        run: |
          echo "## Model metrics" > report.md
          cat metrics.txt >> report.md
          
          echo "## Data visualization" >> report.md
          echo "![inline](feature_importance.png)" >> report.md
          
          cml comment create report.md

      - name: Upload report.md as artifact
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.md

  build_docker_image:
    needs: retraining_model
    runs-on: ubuntu-latest

    steps:
      - name: Check the repo
        uses: actions/checkout@v4

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN  }}

      - name: Build docker image
        run: docker build -t jcourrau/mlops_simple_workflow:dev .

      - name: Docker push to Dockerhub
        run: docker push jcourrau/mlops_simple_workflow:dev